# General Settings
baseurl: "" # The name of your GitHub repository
url: "https://vatosoamananjara-jimmy.com/" # The URL of your GitHub Pages

# Site Information
title: "Mananjara Jimmy VATOSOA"
description: "Cloud Engineer | Machine Learning"

# Theme Settings
theme-color: stone # Options: indigo, yellow, pink, green, stone

# Homepage Information
author: Mananjara Jimmy VATOSOA
author-bio: true  # Change to false to hide author bio
author-image: profile_home.jpg  # File must be in the /assets/img/ folder

# Navigation Menu
show-nav-menu: true

nav-menu:
  - text: RESUME
    permalink: ./assets/raw/Machine_LearningEngineer_Mananjara_Jimmy_VATOSOA_V2.08.pdf
  - text: Experience
    permalink: projects
  - text: About
    permalink: about
  - text: Blog
    permalink: blog

# Social Media Links
twitter: false
facebook: false
instagram: false
github: https://github.com/Jimmy586
linkedin: https://linkedin.com/in/mananjara-jimmy.vatosoa
medium: false
google-scholar: false
email: contact@vatosoamananjara-jimmy.com

# Footer Information
footer-msg: "Powered using Tailpages"
footer-msg-link: https://github.com/Jimmy586

# Google Analytics
google-analytics: 

# Jekyll Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections_dir: collections
collections:
  - academics
  - projects
