# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
url: "https://henriaidasso.me" # the url of your github pages

# site information used in page title, meta data etc.
title: "Henri Aïdasso"
description: Research Scientist

# color theme for links
theme-color: stone # indigo|yellow|pink|green|stone|

# homepage information
author: Henri Aïdasso
author-bio: true  # change to false to hide
author-image: profile_home.jpeg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Publications
  permalink: publications
- text: Teaching
  permalink: teaching
- text: Tools
  permalink: tools
- text: Services
  permalink: services

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: https://github.com/ahenrij
linkedin: https://linkedin.com/in/ahenrij
medium: false
google-scholar: https://scholar.google.ca/citations?user=JYWwzYgAAAAJ&hl=en
email: ahenrij@gmail.com

# footer information
footer-msg: "Powered using Tailpages"
footer-msg-link: https://github.com/ahenrij/tailpages

# google analytics
google-analytics: G-Q7Q1DLKRB4

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
    - jekyll-sitemap

# collections
collections_dir: collections
collections:
  - academics
  - projects
  - publications
  - teachings
  - tools